JSCOE-83 React 18 Features
ModusCreateOrg/js-coe-experiments pull request #10
Opened 2021-12-20 16:05 UTC by JasonOuyang80

2022-01-12 23:50 UTC, michaeltintiuc requested changes
Overall looks good, but better remove the eslint overrides as really the ones added are best practices

2022-01-12 23:50 UTC, michaeltintiuc commented on react-18-features/src/api/fetchData.js
> +/* eslint-disable consistent-return */
Removed commented out code and probably best to not have eslint overrides

2022-01-12 23:50 UTC, michaeltintiuc commented on react-18-features/src/api/fetchGraphQLData.js
> +  // Get the response as JSON
The eslint rules makes sense, best to return a promise that the caller can await on instead

2022-01-19 11:16 UTC, JasonOuyang80 commented on react-18-features/src/api/fetchGraphQLData.js
> +  // Get the response as JSON
Thanks Michael!

2022-01-19 20:14 UTC, michaeltintiuc approved these changes

2022-02-17 12:10 UTC, merged