Jscoe 88 code an experiment that shows how to build module federation with webpack
ModusCreateOrg/js-coe-experiments pull request #14
Opened 2022-01-11 16:48 UTC by vijeysrc

2022-01-11 18:13 UTC, modusjorge requested changes
Code review in general looks good, just left some nitpick about the image links.
Style is a bit scattered with a lot of "magic values", some variables with intuitive names would help on that but since it is an experiment I don't think it's worth the trouble since we won't be reusing everywhere (might want to try styled components for the next since they make this trivial).
Found some empty index files like jscoe-88-module-federation-with-webpack/packages/content-mfe/index.js, not sure if they are really needed, but if not would be nice to remove them to clean up.
Overall the rest looks pretty stellar, nice one!

2022-01-11 18:13 UTC, modusjorge commented on jscoe-88-module-federation-with-webpack/packages/base-app/src/components/Header/Header.jsx
> +          src="https://3lhowb48prep40031529g5yj-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/avatar_user_57_1542388114.png"
would be better to download and commit a generic image here (making sure is not copyrighted XD) instead of linking to a external URL that might brake

2022-01-11 18:13 UTC, modusjorge commented on jscoe-88-module-federation-with-webpack/packages/content-mfe/content/index.json
> +        "image": "https://res.cloudinary.com/modus-create-inc/images/f_auto,q_auto:eco,w_auto/f_auto,q_auto:eco/v1611942530/Modus-Hero-2/Modus-Hero-2.jpg"
same for this file, better download and commit the images

2022-01-11 18:14 UTC, modusjorge approved these changes

2022-01-12 06:08 UTC, vijeysrc commented on jscoe-88-module-federation-with-webpack/packages/base-app/src/components/Header/Header.jsx
> +          src="https://3lhowb48prep40031529g5yj-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/avatar_user_57_1542388114.png"
I just linked the existing image links from our company site https://moduscreate.com/.  
As suggested, I'll download the images to the project folders and refer them from there.

2022-01-12 06:08 UTC, vijeysrc commented on jscoe-88-module-federation-with-webpack/packages/content-mfe/content/index.json
> +        "image": "https://res.cloudinary.com/modus-create-inc/images/f_auto,q_auto:eco,w_auto/f_auto,q_auto:eco/v1611942530/Modus-Hero-2/Modus-Hero-2.jpg"
As suggested, I'll download the images to the project folders and refer them from there.

2022-01-12 23:40 UTC, michaeltintiuc commented
Overall looks good, but I would suggest you create a helper  package that would handle the module federation in such a way that the webpack config was defined in a single place and the MFEs to be loaded would be defined in package.json alongside other dependencies. I don't know if it's too much or if it's in the scope of this experiment or not

2022-01-27 07:20 UTC, vijeysrc commented
> Overall looks good, but I would suggest you create a helper package that would handle the module federation in such a way that the webpack config was defined in a single place and the MFEs to be loaded would be defined in package.json alongside other dependencies. I don't know if it's too much or if it's in the scope of this experiment or not

@michaeltintiuc I've done the changes as suggested.  Keeping all webpack config in one place.  MFEs are passed to that single sourced function.  Please check.

2022-01-31 14:17 UTC, merged